package:
  name: flask_mysql_util
  version: "HEAD"

source:
  git_url: https://github.com/slaclab/flask_mysql_util.git
  git_tag: "HEAD"

build:
  script:
    - pip install --no-deps --disable-pip-version-check .

requirements:
  build:
    - python
    - setuptools
    - pymysql
  run:
    - python
    - setuptools
    - pymysql

about:
  home: https://github.com/slaclab/flask_mysql_util
  license: MIT License